export type IngredientProtocol = { unit: string, value: number }
export type IngredientWithVDProtocol = { unit: string, value: number, vd: number }
export interface WheyProteinProtocol {
  name: string,
  brand: string,
  category: string,
  subCategory: string,
  flavor?: string,
  size: string,
  // generics search sizes in grams: 100g, 500g, 1000g, 2000g ...
  genericSize: number,
  // servings per container
  servings: number,
  // Serving Size About 1 Scoop
  servingSize: number,
  calories: IngredientProtocol | IngredientWithVDProtocol,
  totalFat: IngredientProtocol | IngredientWithVDProtocol,
  saturatedFat: IngredientProtocol | IngredientWithVDProtocol,
  cholesterol: IngredientProtocol | IngredientWithVDProtocol,
  carbohydrate: IngredientProtocol | IngredientWithVDProtocol,
  dietaryFibers?: IngredientProtocol | IngredientWithVDProtocol,
  totalSugars?: IngredientProtocol | IngredientWithVDProtocol,
  protein: IngredientProtocol | IngredientWithVDProtocol,
  biotin?: IngredientProtocol | IngredientWithVDProtocol,
  calcium?: IngredientProtocol | IngredientWithVDProtocol,
  choline?: IngredientProtocol | IngredientWithVDProtocol,
  chrome?: IngredientProtocol | IngredientWithVDProtocol,
  copper?: IngredientProtocol | IngredientWithVDProtocol,
  fluorine?: IngredientProtocol | IngredientWithVDProtocol,
  folicAcid?: IngredientProtocol | IngredientWithVDProtocol,
  iodine?: IngredientProtocol | IngredientWithVDProtocol,
  iron?: IngredientProtocol | IngredientWithVDProtocol,
  magnesium?: IngredientProtocol | IngredientWithVDProtocol,
  manganese?: IngredientProtocol | IngredientWithVDProtocol,
  molybdenum?: IngredientProtocol | IngredientWithVDProtocol,
  niacin?: IngredientProtocol | IngredientWithVDProtocol,
  pantothenicAcid?: IngredientProtocol | IngredientWithVDProtocol,
  phosphorus?: IngredientProtocol | IngredientWithVDProtocol,
  potassium?: IngredientProtocol | IngredientWithVDProtocol,
  riboflvin?: IngredientProtocol | IngredientWithVDProtocol,
  selenium?: IngredientProtocol | IngredientWithVDProtocol,
  sodium?: IngredientProtocol | IngredientWithVDProtocol,
  thiamine?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminA?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminB12?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminB6?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminC?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminD?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminE?: IngredientProtocol | IngredientWithVDProtocol,
  vitaminK?: IngredientProtocol | IngredientWithVDProtocol,
  zinc?: IngredientProtocol | IngredientWithVDProtocol,
  infos: string[],
  ingredients: string[],
  contains?: string[],
}
