const ingredientsList = [
  'Acesulfame Potassium',
  'Artificial Flavor',
  'Bromelain',
  'Calcium Caseinate',
  'Canola Oil',
  'Cellulose Gum',
  'Cocoa Powder',
  'Cocoa',
  'Corn Syrup Solids',
  'Dipotassium Phosphate',
  'Disodium Phosphate',
  'Egg Albumin',
  'Glutamine Peptides',
  'Lactase',
  'Lecithin',
  'Medium Chain Triglycerides',
  'Micellar Casein',
  'Milk Protein Isolate',
  'Mono And Diglycerides',
  'Natural And Artificial Flavors',
  'Natural Flavor',
  'Nonfat Dry Milk',
  'Papain',
  'Polydextrose',
  'Salt',
  'Silicon Dioxide',
  'Sodium Bicarbonate',
  'Sodium Caseinate',
  'Soy Lecithin',
  'Sucralose',
  'Sugar',
  'Sunflower Oil',
  'Tocopherols',
  'Tricalcium Phosphate',
  'Wheat Flour',
  'Whey Peptides',
  'Whey Protein Concentrate',
  'Whey Protein Isolate',
  'Xanthan Gum',
]

export default ingredientsList
